site_name: specfab documentation

nav:
    - About: index.md
    - 'CPO representation':
        - Representation: cpo-representation.md
        - Structure tensors: cpo-structuretensors.md
        - Idealized states: cpo-idealized.md
        - Rotation: cpo-rotation.md
    - 'CPO dynamics':
        - Transversely isotropic grains: cpo-dynamics-tranisotropic.md
        - Orthotropic grains: cpo-dynamics-orthotropic.md
    - 'Viscous':
        - Strain-rate enhancements: enhancements-strainrate.md
        - Constitutive equations: constitutive-viscoplastic.md
    - 'Elastic':
        - Wave propagation: wavepropagation-elastic.md
        - Constitutive equations: constitutive-elastic.md
    - 'Electromagnetic':
        - Wave propagation: wavepropagation-electromagnetic.md
    - 'Further applications': 
        - Radar-derived physical properties: radar-derived-PP.md
        - FEM integration: FEM-integration.md
    - 'Miscellaneous': 
        - Plotting: cpo-plot.md
        - Deformation modes: deformation-modes.md

theme: 
    name: 'readthedocs'

markdown_extensions:
    - attr_list
    - admonition
    - pymdownx.details
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

